"""
This type stub file was generated by pyright.
"""

class TinkoffAPIException(Exception):
    ...


class TinkoffAcquiringAPIClient:
    API_ENDPOINT = ...
    def __init__(self, terminal_key, secret) -> None:
        ...
    
    async def send_request(self, endpoint, params): # -> Any:
        ...
    
    def generate_token(self, params): # -> str:
        ...
    
    async def init_payment(self, amount: float, order_id: any, description: any, receipt=..., success_url: str = ..., fail_url: str = ..., email: str = ...): # -> Any:
        ...
    
    async def get_payment_state(self, payment_id): # -> Any:
        ...
    
    async def confirm_payment(self, payment_id): # -> Any:
        ...
    
    async def cancel_payment(self, payment_id): # -> Any:
        ...
    


