"""
This type stub file was generated by pyright.
"""

from typing import Any

class TinkoffAPIException(Exception): ...

class TinkoffAcquiringAPIClient:
    API_ENDPOINT = ...
    def __init__(self, terminal_key: str | None, secret: str | None) -> None: ...
    async def send_request(self, endpoint: str, params: dict[str, Any]) -> Any: ...
    def generate_token(self, params: dict[str, Any]) -> str: ...
    async def init_payment(
        self,
        amount: float,
        order_id: str | int,
        description: str | int,
        receipt: dict[str, Any] = ...,
        success_url: str = ...,
        fail_url: str = ...,
        email: str = ...,
    ) -> Any: ...
    async def get_payment_state(self, payment_id: str | int | None) -> Any:  # :
        ...

    async def confirm_payment(self, payment_id: str | int | None) -> Any:  # :
        ...

    async def cancel_payment(self, payment_id: str | int | None) -> Any:  # :
        ...
