from pyrogram.types import InlineKeyboardButtonBuy as InlineKeyboardButtonBuy, InlineKeyboardMarkup

class ButtonsMenu:
    @classmethod
    def get_buy_markup(cls, tg_id: int | str) -> InlineKeyboardMarkup: ...
    @staticmethod
    def get_newsletter_markup(tg_id: int | str) -> InlineKeyboardMarkup: ...
    @staticmethod
    def get_start_markup() -> InlineKeyboardMarkup: ...
    @classmethod
    def get_payment_markup(cls, payment_url: str, cost: int) -> InlineKeyboardMarkup: ...
    @staticmethod
    def get_menu_markup() -> InlineKeyboardMarkup: ...
